"""
Train the ML incident categorizer for Adani IMS — Phase 7

Departments: it, security, hr, technical_operations, marketing, legal
100 samples per category = 600 total training samples
Model: TfidfVectorizer(ngram_range=(1,2)) + LogisticRegression(C=10)
Output: app/ml/models/categorizer.joblib
"""

import os
import joblib
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import cross_val_score
from extend_it_training_data import REAL_INSPIRED_SAMPLES, SYNTHETIC_SAMPLES
# ── Training data ─────────────────────────────────────────

IT_SAMPLES = [
    "Server is completely down and employees cannot access internal systems",
    "Network connectivity issues affecting the entire office floor",
    "Data breach detected on production database server",
    "Email system not responding for multiple users since morning",
    "VPN connection failing for all remote workers",
    "Ransomware attack detected on company workstations",
    "Critical business application crashed unexpectedly causing data loss",
    "Hardware failure on primary storage server",
    "Internet connectivity completely down at headquarters building",
    "Cybersecurity incident involving unauthorized access to systems",
    "Wi-Fi network is unavailable across all conference rooms",
    "Antivirus software flagged multiple files as malware",
    "Company website is down and customers cannot access portal",
    "Database server experiencing high load and slow performance",
    "Cloud infrastructure outage affecting multiple services",
    "IT helpdesk system is offline and tickets cannot be raised",
    "Phishing email campaign targeting employee credentials",
    "Software deployment failed causing rollback issues",
    "Firewall configuration error blocking legitimate traffic",
    "Active Directory domain controller failure",
    "ERP system login failure for entire finance department",
    "Backup system failed and last backup is outdated",
    "Critical security patch deployment required immediately",
    "API gateway experiencing intermittent failures",
    "DNS server failure causing name resolution issues",
    "SSL certificate expired causing HTTPS errors",
    "Printer network connectivity lost across all floors",
    "Video conferencing system down before board meeting",
    "Laptop batch corrupted after automatic Windows update",
    "Mobile device management system unresponsive",
    "IT infrastructure monitoring system not sending alerts",
    "Remote desktop access failing for work from home employees",
    "Data center cooling system alert from server room",
    "Storage capacity at 95 percent requiring urgent expansion",
    "Unauthorized USB device detected on secure workstation",
    "Two factor authentication system down",
    "Load balancer misconfiguration causing service outage",
    "Software license expiry disrupting operations",
    "Network switch failure causing segment isolation",
    "Vulnerability scan detected critical CVE in production system",
    "System logs showing repeated failed login attempts",
    "CRM software upgrade failed causing data corruption",
    "IT asset tracking system showing discrepancy",
    "Zoom platform unavailable during scheduled all hands meeting",
    "Internal file sharing server storage full",
    "Kubernetes cluster node failure affecting microservices",
    "Database replication lag causing read inconsistencies",
    "Intrusion detection system triggered multiple alerts",
    "Password reset system unresponsive for locked out users",
    "Network monitoring showing unusual outbound traffic spike",
    "Application server memory leak causing degraded performance",
    "Helpdesk ticket system integration broken",
    "Zero day vulnerability alert from security vendor",
    "Power outage caused unclean shutdown of servers",
    "IT equipment missing from inventory audit",
    "Proxy server configuration preventing internet access",
    "Automated deployment pipeline broken",
    "Employee workstation infected with keylogger",
    "Cloud storage sync failing for executive team",
    "Business intelligence dashboard showing incorrect data",
    "Network printer spooler service crashed",
    "Critical update blocked by incompatible software",
    "Data exfiltration attempt detected by DLP system",
    "IT service desk phone system down",
    "Core banking integration API timing out",
    "Endpoint detection and response alert triggered",
    "Router firmware update caused network disruption",
    "Application deployment to production failed",
    "Digital certificate management system error",
    "Employee unable to access corporate intranet",
    "Security operations center alert escalation",
    "IT vendor access credentials compromised",
    "Slack workspace experiencing message delivery failures",
    "Domain name about to expire requiring renewal",
    "System performance degradation during peak hours",
    "Software compatibility issue after OS upgrade",
    "Network segmentation policy breach detected",
    "Remote monitoring tool lost connectivity to branch offices",
    "Incident response team activated for cyber attack",
    "Database admin locked out of production server",
    "System time synchronization failure causing errors",
    "IT compliance audit finding critical configuration gap",
    "Application crash affecting customer facing portal",
    "Scheduled maintenance window exceeded causing downtime",
    "IT team reporting unusual system behavior",
    "Patch management system showing failed deployments",
    "Network performance degraded due to bandwidth saturation",
    "Critical system alerts not being sent to operations team",
    "Employee reported suspicious software installed on laptop",
    "Server hardware reaching end of life requiring replacement",
    "Configuration management database out of sync",
    "IT disaster recovery drill revealed critical gaps",
    "Cloud provider reported security incident",
    "Automated testing pipeline completely broken",
    "Enterprise software vendor pushing breaking change",
    "Data analytics platform down during monthly close",
    "Employee workstation showing blue screen of death",
    "IT procurement system showing unauthorized purchase order",
    "Network access control blocking legitimate devices",
]
IT_SAMPLES += REAL_INSPIRED_SAMPLES + SYNTHETIC_SAMPLES

SECURITY_SAMPLES = [
    "Unauthorized individual found in restricted server room",
    "Security camera malfunction at main entrance gate",
    "Theft of laptop equipment from employee workstation",
    "Badge access system not working at building gate",
    "Suspicious package found near building entrance lobby",
    "Physical break-in attempt detected at night",
    "Tailgating incident at secure access point",
    "Security guard reported altercation with visitor",
    "Perimeter fence breach detected at eastern boundary",
    "Vehicle without authorization found in restricted parking",
    "Security patrol found unlocked door to sensitive area",
    "Visitor badge not returned after site visit",
    "Security alarm triggered in executive office floor",
    "CCTV footage tampering detected in review",
    "Armed intruder alert in corporate headquarters",
    "Employee reported threatening behavior from colleague",
    "Access card cloning attempt suspected at turnstile",
    "Security incident log showing repeated access failures",
    "Drone detected flying over restricted facility area",
    "Security team found evidence of vandalism",
    "Unauthorized photography in confidential meeting area",
    "Security escort required for sensitive document transfer",
    "Workplace violence incident between two employees",
    "Suspicious individual following employees from parking",
    "Bomb threat received requiring evacuation",
    "Security sweep revealed hidden recording device",
    "Emergency exit door found propped open overnight",
    "Fire suppression system accidentally triggered",
    "Security contractor badge access misuse reported",
    "Impersonation attempt of senior executive at reception",
    "Social engineering attempt on front desk security",
    "Guard post abandoned without authorization",
    "Security rover vehicle breakdown during patrol",
    "Protest gathering outside building requiring response",
    "VIP security detail incident during site visit",
    "Security footage retention policy violation found",
    "Intrusion detected in mail room after hours",
    "Key management system showing missing master keys",
    "Theft of petty cash from finance department safe",
    "Security incident during corporate event",
    "External contractor violated safety and security protocol",
    "Mobile phone recording in confidential boardroom",
    "Security breach during data center physical inspection",
    "Animal intrusion in restricted outdoor facility",
    "Security team responding to medical emergency",
    "Overnight security guard sleeping on duty reported",
    "Unauthorized access to HR records room",
    "Security lighting failure in parking structure",
    "Corporate espionage attempt suspected",
    "Emergency lockdown drill revealed protocol gaps",
    "Building intercom system failure during security event",
    "Visitor management system offline causing access issues",
    "Security incident during executive travel",
    "Physical document shredding policy violation",
    "Security tag not removed from confidential equipment",
    "Suspicious vehicle parked outside facility overnight",
    "Access control panel tampered in maintenance area",
    "Security team coordination failure during drill",
    "Unescorted vendor found in restricted area",
    "Security incident report filing delayed",
    "Motion sensor false alarm investigation required",
    "Security badge database error causing lockouts",
    "Physical penetration test revealed critical weakness",
    "Stolen vehicle used to access facility",
    "Security team understaffed during critical shift",
    "Workplace theft investigation opened",
    "Security response time exceeded SLA threshold",
    "Emergency assembly point blocked by parked vehicles",
    "Security system power backup failure detected",
    "Attempted forced entry at loading dock",
    "Security command center equipment malfunction",
    "Visitor overstayed permitted access window",
    "Security incident during corporate merger announcement",
    "Employee reported being stalked to and from office",
    "Security check revealed contraband in employee bag",
    "Night vision camera offline in critical zone",
    "Security team member injured during patrol",
    "Physical access audit revealed unauthorized accounts",
    "Security bollard malfunction at vehicle entry",
    "Panic button not functioning in isolated office",
    "Security supervisor escalating unresolved incident",
    "Staff threatening resignation citing security concerns",
    "Physical security assessment overdue by three months",
    "External security audit finding medium severity gap",
    "Security team equipment budget request urgent",
    "Two visitors exchanged badges to bypass security",
    "Security guard distracted allowing unauthorized entry",
    "Access log anomaly detected requiring investigation",
    "Physical security policy not followed during office move",
    "Security incident at data destruction event",
    "Guard post communication radio failure",
    "Stolen access card used before deactivation",
    "Security team training compliance gap identified",
    "Physical threat made against company director",
    "After hours building occupancy detected unexpectedly",
    "Security camera coverage gap identified in critical area",
    "Social media threat against company facility received",
    "Security escort policy violated by senior executive",
    "Emergency contact list for security team outdated",
]

HR_SAMPLES = [
    "Employee filed formal harassment complaint against supervisor",
    "Workplace injury requiring medical attention and report",
    "Labor dispute escalating between workers and management",
    "Employee violated code of conduct requiring investigation",
    "New hire onboarding credentials not ready on first day",
    "Payroll processing error affecting multiple employees",
    "Employee termination dispute requiring HR mediation",
    "Mandatory compliance training completion rate below target",
    "Sexual harassment allegation filed against department head",
    "Wrongful termination claim from recently separated employee",
    "Discrimination complaint based on protected characteristic",
    "Employee requesting immediate mental health support",
    "Workplace bullying incident escalated to HR formally",
    "Employee refused to follow reasonable management instruction",
    "Performance improvement plan dispute raised by employee",
    "Annual appraisal scores challenged by multiple employees",
    "HR policy violation during business travel",
    "Employee absent without leave for multiple days",
    "Grievance raised over unfair overtime allocation",
    "Employee reporting hostile work environment",
    "Whistleblower complaint regarding unethical manager behavior",
    "Benefit enrollment error leaving employee without insurance",
    "Employee requesting emergency family leave",
    "HR audit revealed incomplete employee files",
    "Employee drug test positive result handling required",
    "Resignation wave in key department requiring investigation",
    "Employee refused transfer citing family circumstances",
    "HR data privacy breach involving employee records",
    "Collective bargaining agreement violation alleged",
    "Employee accommodation request for disability",
    "Contract worker dispute over unpaid hours",
    "Employee promotion denied without transparent reason",
    "HR system access error preventing policy updates",
    "Exit interview revealing systemic management issue",
    "New hire background verification failure",
    "Employee requested to review employment contract terms",
    "Performance review manipulation alleged by team member",
    "HR failing to address repeat policy violator",
    "Employee retirement benefits calculation error",
    "Mandatory diversity training not completed by deadline",
    "Employee reporting unsafe working conditions to HR",
    "Salary band compression complaints from senior staff",
    "Employee found moonlighting in violation of contract",
    "Reference check revealed falsified credentials in resume",
    "Employee requesting flexible work arrangement denied",
    "HR manager conflict of interest complaint filed",
    "Temporary worker converted to permanent without approval",
    "Employee data exported without authorization by HR staff",
    "Job offer rescinded after background check results",
    "Employee requesting formal grievance hearing",
    "Internal job posting not following fair process",
    "Employee complaint about favoritism in promotions",
    "HR failing to process leave application within SLA",
    "Employee alleged retaliation after safety complaint",
    "Probation extension disputed by new employee",
    "Team leader accused of micromanagement and intimidation",
    "Employee reporting payroll deduction without consent",
    "HR investigation compromised by information leak",
    "Employee seeking protection under whistleblower policy",
    "Mass resignation letter submitted by entire team",
    "Employee refusing mandated return to office policy",
    "HR compliance gap found in labor law adherence",
    "Employee mental health crisis requiring urgent intervention",
    "Workplace accident form not submitted within required time",
    "Employee using sick leave for personal travel discovered",
    "HR department not responding to urgent employee queries",
    "Employee handbook not updated with new policies",
    "Internship agreement violation by hosting department",
    "Employee benefits portal completely unavailable",
    "HR investigation dragging without resolution for months",
    "Employee claiming unsafe night shift conditions",
    "Performance data inconsistency across HR systems",
    "Employee complaint about manager sharing salary information",
    "HR policy exemption granted without proper authority",
    "Termination paperwork not completed within required timeline",
    "Employee requesting transfer due to harassment concerns",
    "HR town hall feedback revealing low morale concerns",
    "Annual salary review delayed without communication",
    "Employee sick leave pattern triggering HR review",
    "HR officer made unauthorized promise to employee",
    "Employee family member hired in violation of nepotism policy",
    "Disciplinary action not documented in employee file",
    "Employee alleging workplace injury due to poor ergonomics",
    "Team conflict escalating requiring HR mediation",
    "HR failing to maintain confidentiality of complaint",
    "Employee unable to access HR self service portal",
    "Onboarding checklist items missed for new batch",
    "Employee complaint about lack of career development support",
    "Leave balance error discovered before year end",
    "HR audit found missing signatures on critical documents",
    "Employee claiming constructive dismissal situation",
    "HR department budget overrun requiring approval",
    "Employee complaint about unequal pay for equal work",
    "Background screening vendor data breach affecting candidates",
    "HR manager taking extended absence without handover",
    "Employee appeal against formal written warning outcome",
    "HR policy changes not communicated to employees",
    "Workplace accident investigation report incomplete",
    "New HR software implementation causing data errors",
    "Employee alleging religious discrimination in scheduling",
]

TECHNICAL_OPERATIONS_SAMPLES = [
    "HVAC system failure causing temperature extremes in building",
    "Elevator malfunction trapping employees between floors",
    "Power generator failure at critical facility",
    "Water pipe burst causing flooding in basement level",
    "Roof structural damage after heavy monsoon rainfall",
    "Electrical fault in main distribution panel building",
    "Facility maintenance equipment breakdown delaying operations",
    "Air conditioning compressor failure in data center area",
    "Backup power UPS system test failure critical",
    "Infrastructure maintenance overdue for critical equipment",
    "Boiler system failure affecting building heating",
    "Plumbing blockage causing sewage backflow in office",
    "Structural crack detected in load bearing wall",
    "Fire suppression system malfunction detected during inspection",
    "Building automation system offline after software update",
    "Critical facility equipment reaching end of service life",
    "Diesel fuel supply low for backup generators",
    "Water treatment system malfunction at facility",
    "Crane breakdown on active construction site",
    "Heavy machinery failure causing production stoppage",
    "Conveyor belt system jammed requiring maintenance",
    "Lift shaft inspection overdue by three months",
    "Gas pipeline pressure abnormality detected",
    "High voltage substation equipment fault",
    "Cooling tower efficiency drop affecting operations",
    "Facility roof waterproofing failure causing leaks",
    "Emergency lighting battery backup failure discovered",
    "Compressed air system pressure loss across facility",
    "Fire door mechanism failure in critical corridor",
    "Sewage pump station overflow risk identified",
    "HVAC duct cleaning overdue causing air quality issues",
    "Technical operations team unable to reach remote site",
    "Critical spare parts shortage delaying repair",
    "Facility power consumption exceeding safety limits",
    "Water storage tank contamination suspected",
    "Structural inspection revealing foundation settlement",
    "Building facade panels loosening creating safety hazard",
    "Emergency exit stairwell lighting failure",
    "Technical operations contractor safety violation",
    "Facility floor loading capacity exceeded by equipment",
    "Vibration levels from machinery exceeding threshold",
    "Waste management system malfunction at facility",
    "Technical operations SLA missed for critical repair",
    "Facility flooding risk due to drainage system blockage",
    "High pressure steam valve failure requiring shutdown",
    "Transformer oil leak detected in electrical room",
    "Parking structure structural assessment overdue",
    "Technical operations vehicle fleet breakdown",
    "Fuel storage tank leak detected at facility",
    "Building energy management system error",
    "Sprinkler system inspection finding multiple failures",
    "HVAC filter replacement overdue across facility",
    "Facility access road damage causing vehicle incident",
    "Emergency shutdown system test failure",
    "Technical operations permit to work not followed",
    "Asbestos survey findings requiring remediation action",
    "Critical facility instrument calibration overdue",
    "Water heating system failure in employee facility",
    "Technical operations handover documentation incomplete",
    "Facility signage missing in critical safety areas",
    "Noise levels exceeding occupational health limits",
    "Vibration isolator failure on critical machinery",
    "Facility maintenance budget depleted before year end",
    "Technical operations team overtime exceeding limits",
    "Safety valve failed to operate during pressure test",
    "Facility security fence structural integrity compromised",
    "Emergency response equipment inspection overdue",
    "Technical operations shift change communication failure",
    "Outdoor lighting failure creating safety risk at night",
    "Facility weighbridge calibration error causing disputes",
    "Technical operations quality audit nonconformance",
    "Building permit for renovation works expired",
    "Cooling system chemical treatment overdue",
    "Facility ventilation system failing pollution tests",
    "Technical operations resource allocation conflict",
    "Emergency generator load test showing insufficient capacity",
    "Pipe insulation deterioration causing heat loss",
    "Facility fire detection zone fault",
    "Technical operations PPE compliance gap identified",
    "Water leak from overhead pipe damaging equipment",
    "Facility capacity expansion blocked by utility limits",
    "Emergency spill containment equipment missing",
    "Technical operations contractor performance below standard",
    "Facility condition assessment revealing multiple issues",
    "Steam trap failure causing energy waste",
    "Technical operations work order backlog critical",
    "Rooftop equipment anchorage failure safety risk",
    "Facility shutdown procedure not followed correctly",
    "Technical operations team skills gap identified",
    "Building inspection failure requiring immediate remediation",
    "Preventive maintenance schedule not being followed",
    "Facility utility metering inaccuracy discovered",
    "Emergency response drill failed technical operations test",
    "Technical documentation missing for critical systems",
    "Facility asset register showing major discrepancies",
    "Structural engineer report requires immediate action",
    "Technical operations incident investigation delayed",
]

MARKETING_SAMPLES = [
    "Marketing campaign materials printed with incorrect brand colors",
    "Brand guidelines violated in external advertisement",
    "Social media crisis requiring immediate response and mitigation",
    "Event logistics failure at major product launch ceremony",
    "Vendor delivered wrong promotional materials before deadline",
    "PR crisis due to negative media coverage of company",
    "Marketing database possibly compromised with customer data",
    "Billboard advertisement contains factual error",
    "Campaign budget significantly overspent without prior approval",
    "Marketing agency failed to deliver assets on deadline",
    "Incorrect pricing published in promotional material",
    "Trademark infringement in recent marketing campaign",
    "Marketing team unauthorized disclosure of upcoming product",
    "Social media account hacked posting inappropriate content",
    "Influencer partnership gone wrong causing reputational damage",
    "Marketing event cancelled last minute by venue",
    "Customer complaint about misleading advertisement claims",
    "Marketing data analytics platform showing incorrect metrics",
    "Competitor campaign copied our creative without permission",
    "Press release distributed with sensitive internal information",
    "Marketing automation system sending incorrect emails to customers",
    "Brand ambassador behavior causing public controversy",
    "Marketing material translation error in regional campaign",
    "Product photography not meeting quality standards for launch",
    "Marketing approval workflow bypassed for urgent campaign",
    "Customer segmentation data used incorrectly in campaign",
    "Marketing agency invoicing error requiring financial review",
    "Campaign performance significantly below projected targets",
    "Marketing team member leaked campaign strategy to competitor",
    "Digital advertisement placed on inappropriate website",
    "Marketing survey data collection violating privacy law",
    "Event sponsorship agreement dispute with partner",
    "Marketing content using unauthorized celebrity image",
    "Campaign metrics reporting discrepancy between teams",
    "Marketing budget reallocation without finance approval",
    "Product launch campaign delayed due to regulatory clearance",
    "Marketing collateral recall required due to error",
    "Social media scheduled post went out incorrectly",
    "Marketing team failing to archive campaign materials",
    "Brand consistency issue across regional marketing",
    "Marketing communication sent to wrong customer segment",
    "Public relations firm not delivering agreed coverage",
    "Marketing event injury to attendee requiring report",
    "Campaign analysis revealing data collection breach",
    "Marketing software contract expiring without renewal plan",
    "Media buying error resulting in wasted advertising spend",
    "Marketing performance dashboard inaccessible during review",
    "Campaign A/B test results manipulated by team member",
    "Marketing vendor NDA breach discovered",
    "Customer competition prize not delivered as promised",
    "Marketing team missing critical project milestone",
    "Advertising standards authority complaint received",
    "Marketing fraud suspected in affiliate program",
    "Brand monitoring alert for negative trending content",
    "Marketing team conflict over campaign creative direction",
    "Product claims in advertisement not substantiated",
    "Marketing calendar not updated causing double booking",
    "Crisis communication plan not activated when required",
    "Marketing team overtime and burnout reaching critical level",
    "Competitor negative campaign targeting our brand",
    "Marketing analytics showing website traffic manipulation",
    "Event registration system failure before major conference",
    "Marketing email unsubscribe link not working",
    "Campaign creative assets lost due to storage failure",
    "Marketing team head resigned during critical campaign",
    "Brand survey results showing declining awareness",
    "Marketing partnership contract terms dispute",
    "Social media comment escalation requiring brand response",
    "Marketing material distributed without legal clearance",
    "Campaign targeting sensitive demographic without approval",
    "Marketing team security awareness training not completed",
    "Product recall communication strategy required urgently",
    "Marketing spend audit revealing undisclosed vendor relationships",
    "Campaign launch blocked by last minute legal concern",
    "Marketing research firm data quality issues discovered",
    "Brand guidelines document needs urgent update",
    "Marketing team member copyright violation in content",
    "Campaign localization failing cultural sensitivity check",
    "Marketing technology stack integration broken",
    "PR agency conflict of interest discovered",
    "Marketing event health and safety assessment incomplete",
    "Brand crisis simulation revealed major process gaps",
    "Marketing team knowledge transfer gap before major campaign",
    "Campaign ROI calculation methodology dispute",
    "Marketing material disposal not following policy",
    "Brand perception dropping in key customer segment",
    "Marketing team hiring delayed for critical role",
    "Campaign social media policy violation discovered",
    "Marketing vendor performance review overdue",
    "Brand event security incident requiring investigation",
    "Marketing team project management tool access issues",
    "Campaign image rights expired requiring replacement",
    "Marketing compliance checklist not completed",
    "Brand ambassador contract renewal not actioned",
    "Marketing analytics data retention policy breach",
    "Campaign approval delayed causing launch risk",
    "Marketing team offsite security incident",
    "Brand monitoring tool subscription lapsed",
    "Marketing communication tone policy violation",
    "Campaign creative rejected at last minute",
]

LEGAL_SAMPLES = [
    "Regulatory compliance violation reported by internal auditor",
    "Legal notice received from government regulatory authority",
    "Contract dispute with major supplier escalating",
    "Intellectual property infringement claim filed against company",
    "Environmental regulation non-compliance detected at site",
    "Litigation threat from former business partner received",
    "GDPR data protection violation reported to legal team",
    "Tax compliance issue identified requiring urgent resolution",
    "Business license renewal missed causing operational risk",
    "Former employee filed lawsuit against company",
    "Shareholder derivative action threat received",
    "Competition law violation investigation opened",
    "Export control compliance failure discovered",
    "Consumer protection law complaint escalated to legal",
    "Employment tribunal case requiring legal representation",
    "Data subject access request not responded to in time",
    "Legal contract signed without proper authorization",
    "Whistleblower legal protection obligation triggered",
    "Anti-bribery compliance breach investigation",
    "Legal entity registration details require urgent update",
    "Court injunction received affecting business operations",
    "Legal hold notice not implemented correctly on data",
    "Regulatory inspection finding requiring legal response",
    "Merger clearance filing deadline at risk",
    "Legal advisor conflict of interest identified",
    "Contract renewal missed with key service provider",
    "Defamation claim from competitor requiring response",
    "Legal document notarization overdue for transaction",
    "Statutory audit qualification requiring legal action",
    "Deposition subpoena received for senior executive",
    "Patent filing deadline missed for new invention",
    "Legal compliance training not completed by team",
    "Class action lawsuit filed by customer group",
    "Anti-money laundering suspicious transaction report",
    "Legal entity dissolution not completed properly",
    "Regulatory filing deadline missed with authority",
    "Employment contract terms dispute with contractor",
    "Legal matter escalated without proper authorization",
    "Competition authority dawn raid requiring legal response",
    "Legal billing dispute with external law firm",
    "Corporate governance policy violation identified",
    "Contract performance guarantee claim received",
    "Legal entity beneficial ownership not updated",
    "Cross border transaction legal compliance failure",
    "Arbitration award enforcement required",
    "Legal document retention policy violation found",
    "Regulatory sanction letter received requiring response",
    "Corporate secretary compliance deadline missed",
    "Legal risk assessment overdue for major project",
    "Indemnity claim under contract submitted",
    "Legal team bandwidth critical before major deal",
    "Statute of limitations risk identified in pending case",
    "Non-disclosure agreement breach suspected",
    "Legal entity annual return filing overdue",
    "Regulatory enforcement action threat received",
    "Force majeure clause invocation required",
    "Contract assignment without required consent",
    "Legal opinion delayed causing deal closure risk",
    "Insolvency proceeding threat from creditor",
    "Corporate resolution not properly executed",
    "Legal dispute over intellectual property ownership",
    "Regulatory approval expiry for business activity",
    "Legal compliance gap in subsidiary operations",
    "Personal injury claim against company facility",
    "Legal matter confidentiality breach by staff member",
    "Environmental remediation legal obligation triggered",
    "Regulatory change requiring immediate policy update",
    "Contract ambiguity causing operational dispute",
    "Legal notification service failure in jurisdiction",
    "Tribunal hearing preparation incomplete",
    "Legal software system outage before critical deadline",
    "Compliance certificate expiry requiring urgent renewal",
    "Legal entity name change not updated in contracts",
    "Regulatory reporting deadline missed",
    "Legal dispute over service delivery terms",
    "Litigation settlement approval required urgently",
    "Legal team failing to meet response SLA",
    "Contract counterparty insolvency discovered",
    "Legal due diligence incomplete before transaction",
    "Regulatory fine received requiring payment and appeal",
    "Legal hold not released after matter concluded",
    "Corporate signatory authority matrix outdated",
    "Legal matter budget significantly exceeded",
    "Regulatory examination scheduled without preparation",
    "Contract dispute mediation appointment missed",
    "Legal advice privileged communication leaked",
    "Compliance program effectiveness gap found",
    "Legal entity consolidation compliance failure",
    "Regulatory notification not sent within required time",
    "Legal matter escalated to board requiring preparation",
    "Contract template used without required customization",
    "Legal risk register not updated for six months",
    "Regulatory relationship management gap identified",
    "Legal team knowledge management system broken",
    "Court filing deadline at critical risk",
    "Compliance audit preparation materials incomplete",
    "Legal entity dividend compliance issue",
    "Regulatory horizon scanning gap identified",
    "Legal matter tracking system data loss",
]

# ── Build dataset ─────────────────────────────────────────

SAMPLES = (
    [(text, "it")                   for text in IT_SAMPLES] +
    [(text, "security")             for text in SECURITY_SAMPLES] +
    [(text, "hr")                   for text in HR_SAMPLES] +
    [(text, "technical_operations") for text in TECHNICAL_OPERATIONS_SAMPLES] +
    [(text, "marketing")            for text in MARKETING_SAMPLES] +
    [(text, "legal")                for text in LEGAL_SAMPLES]
)

import random
random.seed(42)
random.shuffle(SAMPLES)

X = [s[0] for s in SAMPLES]
y = [s[1] for s in SAMPLES]

print(f"Total training samples: {len(SAMPLES)}")
from collections import Counter
print("Distribution:", Counter(y))

# ── Train pipeline ────────────────────────────────────────

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1, 2),
        min_df=1,
        max_features=8000,
        sublinear_tf=True,
    )),
    ("clf", LogisticRegression(
        C=10,
        max_iter=1000,
        class_weight="balanced",
        random_state=42,
    )),
])

# Cross-validation
scores = cross_val_score(pipeline, X, y, cv=5, scoring="accuracy")
print(f"\n5-fold CV accuracy: {scores.mean():.3f} ± {scores.std():.3f}")

# Final fit on all data
pipeline.fit(X, y)

# Quick sanity check
test_cases = [
    ("Server down network outage", "it"),
    ("Security camera malfunction unauthorized entry", "security"),
    ("Employee harassment complaint HR investigation", "hr"),
    ("HVAC failure building maintenance required", "technical_operations"),
    ("Social media crisis brand reputation damage", "marketing"),
    ("Regulatory compliance violation legal notice", "legal"),
]

print("\nSanity checks:")
for text, expected in test_cases:
    proba = pipeline.predict_proba([text])[0]
    predicted = pipeline.classes_[proba.argmax()]
    confidence = proba.max()
    status = "✅" if predicted == expected else "❌"
    print(f"  {status} '{text[:45]}...' → {predicted} ({confidence:.2f}) [expected: {expected}]")

# ── Save model ────────────────────────────────────────────

os.makedirs("app/ml/models", exist_ok=True)
model_path = "app/ml/models/categorizer.joblib"
joblib.dump(pipeline, model_path)
print(f"\n✅ Model saved to {model_path}")
print(f"   File size: {os.path.getsize(model_path) / 1024:.1f} KB")
